name: Build, Pack, and Hand-off to Octopus

on:
  push:
    branches:
    - 'master'
    - 'f/**'
  pull_request:
    branches: [ master ]

env:  
  OUTPUT_FOLDER: PackagesOutput
  PACKAGE_NAME: RandomQuotes
  OCTOPUS_PROJECT_NAME: RandomQuotes  
  OCTOPUS_SPACE_NAME: Default

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get version number      
      run: |
        echo "::set-env name=PACKAGE_VERSION::$(cat versionprefix.txt)"
        echo "PACKAGE_VERSION is: ${env:PACKAGE_VERSION}"  
        echo "OUTPUT_FOLDER is: ${env:OUTPUT_FOLDER}" 
        echo "PACKAGE_NAME is: ${env:PACKAGE_NAME}"
        echo "OCTOPUS_PROJECT_NAME is: ${env:OCTOPUS_PROJECT_NAME}"  
        echo "OCTOPUS_SPACE_NAME is: ${env:OCTOPUS_SPACE_NAME}"      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish
      run: dotnet publish --output PackagesOutput
    - name: Install Octopus Tooling
      run: |
        sudo apt update && sudo apt install --no-install-recommends gnupg curl ca-certificates apt-transport-https && \
        curl -sSfL https://apt.octopus.com/public.key | sudo apt-key add - && \
        sudo sh -c "echo deb https://apt.octopus.com/ stable main > /etc/apt/sources.list.d/octopus.com.list" && \
        sudo apt update && sudo apt install octopuscli
    - name: Pack
      run: octo pack ${env:OUTPUT_FOLDER} --id="${env:PACKAGE_NAME}" --version="${env:PACKAGE_VERSION}"
    - name: Handoff to Octopus Deploy
      env:
        OCTOPUS_URL: ${{ secrets.OCTOPUS_SERVER_URL }}
        OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_API_KEY }}        
      run: octo push --package="${env:PACKAGE_NAME}.${env:PACKAGE_VERSION}.nupkg" --server="${env:OCTOPUS_URL}" --apiKey="${env:OCTOPUS_API_KEY}" --space="${env:OCTOPUS_SPACE_NAME}"  
